version: '3.7'

services:
  frontend:
    container_name: cards-game-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    restart: always
    depends_on:
      - backend
    stdin_open: true
    tty: true
  backend:
    container_name: cards-game-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 5050:5050
    restart: always